matrix:
  include:
  # linux native
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-5.0
        - george-edison55-precise-backports
        packages:
        - clang-5.0
        - gcc-6
        - g++-6
        - wget
        - make
        - git
        - nodejs
        - npm
        - cmake
        - cmake-data
    #    env:
#    - MATRIX_EVAL="CC=clang && CXX=clang++"
#    - BUILD_TYPE=native
    group: travis_latest
    dist: xenial
    language: node_js
    node_js:
    - "iojs"
    - "8"

before_script:
- apt install cmake
- cmake --version
- TRAVIS_TAG=`date +%Y-%m-%d`
- uname -a

script:
- ./build/buildLinuxMac.sh

before_deploy:
- echo tolsta $TRAVIS_OS_NAME $BUILD_TYPE $TRAVIS_BRANCH $TRAVIS_TAG

deploy:
- provider: releases
  api_key:
    secure: MfsqovFmQorr7+r1Y0SlKpfi4SlCCLzkzefCMDDRtnib8h5oWt6ZlNxpQP2EwIx9QVsF3RR+BucRiQ/jc1daeQgBSRjUyTJAFRutigFvNbcoCZ5f3a1VAI1EqmBaDuMKdimtd9KEpYfJhI92tgVz2nf/CmcYYV0ylz5/R5KC8qJbGyhlww8Brcij2s1/yUtiLsupeBsfpmx9t96HcRDCnSD27h5mP3SANeTT1u2NJJtLXLFEmz/Zk6M3ziDKuw7Dvu7fZL7gUH2ofC6+9Q3bSLbTIsSYMbC9gWrdbWNPSWiSK/hd4Y8yB3KwDqLP7jJ/2sLze9NlyDftdGHoazC6Cyq0FmUyQkLUXSH6y7XyzoHuSMhy9Z07HoHRjcm3HxOPE5nfxDDsAKuPcyW9wS5E/Z/MNBHcJdwOacRic+haA88kXvo1Gg5XgayBch5EHYPod6hTdUC7U3y3LW2fmhIvSG8jU+lkkKdb3cY6wd9iGMyJuWjXcvYVMsjCGW5I8hdC4ntWDh0dFAtZd+MStH4mUuuAYBVvBDiVkc8UxF8WP5ZwP3WSwdGm6z867Hg+tI3osqP9yDfuEHWilBJLZQzDE93DyOQtfKabmQHQU6mRUZS0DY2h8z5Tz0GOAI6xmUmNbr16yrPdgDJzqBygpiKFiZUsET+XZEjEnAMUB/h8hhg=
  file: dist/*
#  - ./dist/gdcmanon.js
#  - ./dist/gdcmcheck.js
#  - ./dist/gdcmconv.js
#  - ./dist/gdcmdictdump.js
#  - ./dist/gdcmdiff.js
#  - ./dist/gdcmdump.js
#  - ./dist/gdcmfile.js
#  - ./dist/gdcmgendir.js
#  - ./dist/gdcmimg.js
#  - ./dist/gdcmkey.js
#  - ./dist/gdcmoverlay.js
#  - ./dist/gdcmpap3.js
#  - ./dist/gdcmraw.js
#  - ./dist/gdcmscanner.js
#  - ./dist/gdcmtar.js
#  - ./dist/gdcmxml.js
#  - ./dist/pdf2dcm.js
  skip_cleanup: true
  on:
    repo: InfiniBrains/gdcm-js
#    condition: $BUILD_TYPE = windows
    os: linux
    branches:
      except:
      - gh-pages